# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish "BoarDuck.NET/BoarDuck.NET.csproj" -c "Release" -p:PublishProfile="publish"
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Rsync deploy
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzc
        path: BoarDuck.NET/bin/Release/net8.0/publish/
        remote_path: ${{ secrets.DEPLOY_REMOTE_PATH }}
        remote_host: ${{ secrets.DEPLOY_REMOTE_HOST }}
        remote_port: ${{ secrets.DEPLOY_REMOTE_PORT }}
        remote_user: ${{ secrets.DEPLOY_REMOTE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
    - name: Execute restart script
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_REMOTE_HOST }}
        port: ${{ secrets.DEPLOY_REMOTE_PORT }}
        username: ${{ secrets.DEPLOY_REMOTE_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: ${{ secrets.DEPLOY_RESTART_SCRIPT_COMMAND }}
